#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# codes are at https://w3c.github.io/uievents-code/#code-value-tables
RAW_TABLE=https://raw.githubusercontent.com/w3c/uievents-code/gh-pages/impl-report.txt

 curl $RAW_TABLE | awk 'BEGIN { print "// Autogenerated by gen_keys.sh\n/** @category Input codes */\nexport const keys = {" } END { print "} as const" } /CODE_IMPL / && $3 == "Y" { printf "/** %s *\/\n%s: \"%s\",\n", $0, $2, $2 }' > keys.ts