// Autogenerated by gen_keys.sh
/** @category Input codes */
export const keys = {
/** 			CODE_IMPL Backquote					Y		Y		Y			Y		Y		Y			Y		Y */
Backquote: "Backquote",
/** 			CODE_IMPL Backslash					Y		Y		Y			Y		Y		Y			Y		Y */
Backslash: "Backslash",
/** 			CODE_IMPL BracketLeft				Y		Y		Y			Y		Y		Y			Y		Y */
BracketLeft: "BracketLeft",
/** 			CODE_IMPL BracketRight				Y		Y		Y			Y		Y		Y			Y		Y */
BracketRight: "BracketRight",
/** 			CODE_IMPL Comma						Y		Y		Y			Y		Y		Y			Y		Y */
Comma: "Comma",
/** 			CODE_IMPL Digit0					Y		Y		Y			Y		Y		Y			Y		Y */
Digit0: "Digit0",
/** 			CODE_IMPL Digit1					Y		Y		Y			Y		Y		Y			Y		Y */
Digit1: "Digit1",
/** 			CODE_IMPL Digit2					Y		Y		Y			Y		Y		Y			Y		Y */
Digit2: "Digit2",
/** 			CODE_IMPL Digit3					Y		Y		Y			Y		Y		Y			Y		Y */
Digit3: "Digit3",
/** 			CODE_IMPL Digit4					Y		Y		Y			Y		Y		Y			Y		Y */
Digit4: "Digit4",
/** 			CODE_IMPL Digit5					Y		Y		Y			Y		Y		Y			Y		Y */
Digit5: "Digit5",
/** 			CODE_IMPL Digit6					Y		Y		Y			Y		Y		Y			Y		Y */
Digit6: "Digit6",
/** 			CODE_IMPL Digit7					Y		Y		Y			Y		Y		Y			Y		Y */
Digit7: "Digit7",
/** 			CODE_IMPL Digit8					Y		Y		Y			Y		Y		Y			Y		Y */
Digit8: "Digit8",
/** 			CODE_IMPL Digit9					Y		Y		Y			Y		Y		Y			Y		Y */
Digit9: "Digit9",
/** 			CODE_IMPL Equal						Y		Y		Y			Y		Y		Y			Y		Y */
Equal: "Equal",
/** 			CODE_IMPL IntlBackslash				Y		Y		Y			Y		Y		F			Y		Y		Safari swaps IntlBackslash with Backquote on keyboards that support IntlBackslash */
IntlBackslash: "IntlBackslash",
/** 			CODE_IMPL IntlRo					Y		Y		Y			?		?		?			?		? */
IntlRo: "IntlRo",
/** 			CODE_IMPL IntlYen					Y		Y		Y			?		?		?			?		? */
IntlYen: "IntlYen",
/** 			CODE_IMPL KeyA						Y		Y		Y			Y		Y		Y			Y		Y */
KeyA: "KeyA",
/** 			CODE_IMPL KeyB						Y		Y		Y			Y		Y		Y			Y		Y */
KeyB: "KeyB",
/** 			CODE_IMPL KeyC						Y		Y		Y			Y		Y		Y			Y		Y */
KeyC: "KeyC",
/** 			CODE_IMPL KeyD						Y		Y		Y			Y		Y		Y			Y		Y */
KeyD: "KeyD",
/** 			CODE_IMPL KeyE						Y		Y		Y			Y		Y		Y			Y		Y */
KeyE: "KeyE",
/** 			CODE_IMPL KeyF						Y		Y		Y			Y		Y		Y			Y		Y */
KeyF: "KeyF",
/** 			CODE_IMPL KeyG						Y		Y		Y			Y		Y		Y			Y		Y */
KeyG: "KeyG",
/** 			CODE_IMPL KeyH						Y		Y		Y			Y		Y		Y			Y		Y */
KeyH: "KeyH",
/** 			CODE_IMPL KeyI						Y		Y		Y			Y		Y		Y			Y		Y */
KeyI: "KeyI",
/** 			CODE_IMPL KeyJ						Y		Y		Y			Y		Y		Y			Y		Y */
KeyJ: "KeyJ",
/** 			CODE_IMPL KeyK						Y		Y		Y			Y		Y		Y			Y		Y */
KeyK: "KeyK",
/** 			CODE_IMPL KeyL						Y		Y		Y			Y		Y		Y			Y		Y */
KeyL: "KeyL",
/** 			CODE_IMPL KeyM						Y		Y		Y			Y		Y		Y			Y		Y */
KeyM: "KeyM",
/** 			CODE_IMPL KeyN						Y		Y		Y			Y		Y		Y			Y		Y */
KeyN: "KeyN",
/** 			CODE_IMPL KeyO						Y		Y		Y			Y		Y		Y			Y		Y */
KeyO: "KeyO",
/** 			CODE_IMPL KeyP						Y		Y		Y			Y		Y		Y			Y		Y */
KeyP: "KeyP",
/** 			CODE_IMPL KeyQ						Y		Y		Y			Y		Y		Y			Y		Y */
KeyQ: "KeyQ",
/** 			CODE_IMPL KeyR						Y		Y		Y			Y		Y		Y			Y		Y */
KeyR: "KeyR",
/** 			CODE_IMPL KeyS						Y		Y		Y			Y		Y		Y			Y		Y */
KeyS: "KeyS",
/** 			CODE_IMPL KeyT						Y		Y		Y			Y		Y		Y			Y		Y */
KeyT: "KeyT",
/** 			CODE_IMPL KeyU						Y		Y		Y			Y		Y		Y			Y		Y */
KeyU: "KeyU",
/** 			CODE_IMPL KeyV						Y		Y		Y			Y		Y		Y			Y		Y */
KeyV: "KeyV",
/** 			CODE_IMPL KeyW						Y		Y		Y			Y		Y		Y			Y		Y */
KeyW: "KeyW",
/** 			CODE_IMPL KeyX						Y		Y		Y			Y		Y		Y			Y		Y */
KeyX: "KeyX",
/** 			CODE_IMPL KeyY						Y		Y		Y			Y		Y		Y			Y		Y */
KeyY: "KeyY",
/** 			CODE_IMPL KeyZ						Y		Y		Y			Y		Y		Y			Y		Y */
KeyZ: "KeyZ",
/** 			CODE_IMPL Minus						Y		Y		Y			Y		Y		Y			Y		Y */
Minus: "Minus",
/** 			CODE_IMPL Period					Y		Y		Y			Y		Y		Y			Y		Y */
Period: "Period",
/** 			CODE_IMPL Quote						Y		Y		Y			Y		Y		Y			Y		Y */
Quote: "Quote",
/** 			CODE_IMPL Semicolon					Y		Y		Y			Y		Y		Y			Y		Y */
Semicolon: "Semicolon",
/** 			CODE_IMPL Slash						Y		Y		Y			Y		Y		Y			Y		Y */
Slash: "Slash",
/** 			CODE_IMPL AltLeft					Y		Y		Y			Y		Y		Y			Y		Y */
AltLeft: "AltLeft",
/** 			CODE_IMPL AltRight					Y		Y		Y			Y		Y		Y			Y		Y */
AltRight: "AltRight",
/** 			CODE_IMPL Backspace					Y		Y		Y			Y		Y		Y			Y		Y */
Backspace: "Backspace",
/** 			CODE_IMPL CapsLock					Y		Y		Y			Y		Y		Y			Y		Y */
CapsLock: "CapsLock",
/** 			CODE_IMPL ContextMenu				Y		Y		Y			Y		Y		F			Y		Y		Safari returns "Unidentified" */
ContextMenu: "ContextMenu",
/** 			CODE_IMPL ControlLeft				Y		Y		Y			Y		Y		Y			Y		Y */
ControlLeft: "ControlLeft",
/** 			CODE_IMPL ControlRight				Y		Y		Y			Y		Y		Y			Y		Y */
ControlRight: "ControlRight",
/** 			CODE_IMPL Enter						Y		Y		Y			Y		Y		Y			Y		Y */
Enter: "Enter",
/** 			CODE_IMPL MetaLeft					Y		F		Y			Y		F		Y			Y		F		Firefox returns "OSLeft" */
MetaLeft: "MetaLeft",
/** 			CODE_IMPL MetaRight					Y		F		Y			Y		F		Y			Y		F		Firefox returns "OSRight" */
MetaRight: "MetaRight",
/** 			CODE_IMPL ShiftLeft					Y		Y		Y			Y		Y		Y			Y		Y */
ShiftLeft: "ShiftLeft",
/** 			CODE_IMPL ShiftRight				Y		Y		Y			Y		Y		Y			Y		Y */
ShiftRight: "ShiftRight",
/** 			CODE_IMPL Space						Y		Y		Y			Y		Y		Y			Y		Y */
Space: "Space",
/** 			CODE_IMPL Tab						Y		Y		Y			Y		Y		Y			Y		Y */
Tab: "Tab",
/** 			CODE_IMPL Convert					Y		Y		Y			?		?		?			?		? */
Convert: "Convert",
/** 			CODE_IMPL KanaMode					Y		Y		Y			?		?		?			?		? */
KanaMode: "KanaMode",
/** 			CODE_IMPL NonConvert				Y		Y		Y			?		?		?			?		? */
NonConvert: "NonConvert",
/** 			CODE_IMPL Delete					Y		Y		Y			Y		Y		Y			Y		Y */
Delete: "Delete",
/** 			CODE_IMPL End						Y		Y		Y			Y		Y		Y			Y		Y */
End: "End",
/** 			CODE_IMPL Home						Y		Y		Y			Y		Y		Y			Y		Y */
Home: "Home",
/** 			CODE_IMPL Insert					Y		Y		Y			Y		Y		F			Y		Y		Safari returns "Help" */
Insert: "Insert",
/** 			CODE_IMPL PageDown					Y		Y		Y			Y		Y		Y			Y		Y */
PageDown: "PageDown",
/** 			CODE_IMPL PageUp					Y		Y		Y			Y		Y		Y			Y		Y */
PageUp: "PageUp",
/** 			CODE_IMPL ArrowDown					Y		Y		Y			Y		Y		Y			Y		Y */
ArrowDown: "ArrowDown",
/** 			CODE_IMPL ArrowLeft					Y		Y		Y			Y		Y		Y			Y		Y */
ArrowLeft: "ArrowLeft",
/** 			CODE_IMPL ArrowRight				Y		Y		Y			Y		Y		Y			Y		Y */
ArrowRight: "ArrowRight",
/** 			CODE_IMPL ArrowUp					Y		Y		Y			Y		Y		Y			Y		Y */
ArrowUp: "ArrowUp",
/** 			CODE_IMPL NumLock					Y		?		Y			Y		Y		Y			Y		Y */
NumLock: "NumLock",
/** 			CODE_IMPL Numpad0					Y		?		Y			Y		Y		Y			Y		Y */
Numpad0: "Numpad0",
/** 			CODE_IMPL Numpad1					Y		?		Y			Y		Y		Y			Y		Y */
Numpad1: "Numpad1",
/** 			CODE_IMPL Numpad2					Y		?		Y			Y		Y		Y			Y		Y */
Numpad2: "Numpad2",
/** 			CODE_IMPL Numpad3					Y		?		Y			Y		Y		Y			Y		Y */
Numpad3: "Numpad3",
/** 			CODE_IMPL Numpad4					Y		?		Y			Y		Y		Y			Y		Y */
Numpad4: "Numpad4",
/** 			CODE_IMPL Numpad5					Y		?		Y			Y		Y		Y			Y		Y */
Numpad5: "Numpad5",
/** 			CODE_IMPL Numpad6					Y		?		Y			Y		Y		Y			Y		Y */
Numpad6: "Numpad6",
/** 			CODE_IMPL Numpad7					Y		?		Y			Y		Y		Y			Y		Y */
Numpad7: "Numpad7",
/** 			CODE_IMPL Numpad8					Y		?		Y			Y		Y		Y			Y		Y */
Numpad8: "Numpad8",
/** 			CODE_IMPL Numpad9					Y		?		Y			Y		Y		Y			Y		Y */
Numpad9: "Numpad9",
/** 			CODE_IMPL NumpadAdd					Y		?		Y			Y		Y		Y			Y		Y */
NumpadAdd: "NumpadAdd",
/** 			CODE_IMPL NumpadDecimal				Y		?		Y			Y		Y		Y			Y		Y */
NumpadDecimal: "NumpadDecimal",
/** 			CODE_IMPL NumpadDivide				Y		?		Y			Y		Y		Y			Y		Y */
NumpadDivide: "NumpadDivide",
/** 			CODE_IMPL NumpadEnter				Y		?		Y			Y		Y		Y			Y		Y */
NumpadEnter: "NumpadEnter",
/** 			CODE_IMPL NumpadMultiply			Y		?		Y			Y		Y		Y			Y		Y */
NumpadMultiply: "NumpadMultiply",
/** 			CODE_IMPL NumpadSubtract			Y		?		Y			Y		Y		Y			Y		Y */
NumpadSubtract: "NumpadSubtract",
/** 			CODE_IMPL Escape					Y		Y		Y			Y		Y		Y			Y		Y */
Escape: "Escape",
/** 			CODE_IMPL F1						Y		Y		Y			Y		Y		Y			Y		Y */
F1: "F1",
/** 			CODE_IMPL F2						Y		Y		Y			Y		Y		Y			Y		Y */
F2: "F2",
/** 			CODE_IMPL F3						Y		Y		Y			Y		Y		Y			Y		Y */
F3: "F3",
/** 			CODE_IMPL F4						Y		Y		Y			Y		Y		Y			Y		Y */
F4: "F4",
/** 			CODE_IMPL F5						Y		Y		Y			Y		Y		Y			Y		Y */
F5: "F5",
/** 			CODE_IMPL F6						Y		Y		Y			Y		Y		Y			Y		Y */
F6: "F6",
/** 			CODE_IMPL F7						Y		Y		Y			Y		Y		Y			Y		Y */
F7: "F7",
/** 			CODE_IMPL F8						Y		Y		Y			Y		Y		Y			Y		Y */
F8: "F8",
/** 			CODE_IMPL F9						Y		Y		Y			Y		Y		Y			Y		Y */
F9: "F9",
/** 			CODE_IMPL F10						Y		Y		Y			Y		Y		Y			Y		Y */
F10: "F10",
/** 			CODE_IMPL F11						Y		Y		Y			Y		?		?			Y		?		macOS & Ubuntu enter fullscreen; Chrome requires KeyboardLock */
F11: "F11",
/** 			CODE_IMPL F12						Y		Y		Y			Y		Y		Y			?		? */
F12: "F12",
/** 			CODE_IMPL PrintScreen				Y		Y		Y			F		F		F			?		?		macOS returns "F13"; Ubuntu takes screenshot */
PrintScreen: "PrintScreen",
/** 			CODE_IMPL ScrollLock				Y		Y		Y			?		?		?			Y		Y		macOS decreases brightness */
ScrollLock: "ScrollLock",
/** 			CODE_IMPL Pause						Y		Y		Y			?		?		?			Y		Y		macOS increases brightness */
Pause: "Pause",
/** 			CODE_IMPL Unidentified				Y		Y		Y			Y		Y		Y			Y		Y */
Unidentified: "Unidentified",
/** 			CODE_IMPL BrowserBack				Y		Y		Y			F		F		F			Y		?		Handled by OS (Chrome requires KeyboardLock) */
BrowserBack: "BrowserBack",
/** 			CODE_IMPL BrowserFavorites			Y		Y		Y			F		F		F			Y		?		Handled by OS (Chrome requires KeyboardLock) */
BrowserFavorites: "BrowserFavorites",
/** 			CODE_IMPL BrowserForward			Y		Y		Y			F		F		F			Y		?		Handled by OS (Chrome requires KeyboardLock) */
BrowserForward: "BrowserForward",
/** 			CODE_IMPL BrowserHome				Y		?		Y			F		F		F			Y		?		Handled by OS (Chrome requires KeyboardLock) */
BrowserHome: "BrowserHome",
/** 			CODE_IMPL NumpadEqual				Y		?		Y			Y		?		?			Y		Y */
NumpadEqual: "NumpadEqual",
/** 			CODE_IMPL NumpadParenLeft			Y		?		?			F		?		?			Y		Y */
NumpadParenLeft: "NumpadParenLeft",
/** 			CODE_IMPL NumpadParenRight			Y		?		?			F		?		?			Y		Y */
NumpadParenRight: "NumpadParenRight",
} as const
